FROM yodafrog.sas.jfrog.internal:5001/nginx:latest

MAINTAINER Eran Blumenthal eranb@jfrog.com

RUN /bin/bash -c cd ~; cd /home ; mkdir -p exec
ADD dependencies/jdk-8-linux-x64.tar.gz /home/exec
RUN /bin/bash -c cd /home/exec; mv /home/exec/jdk1* /home/exec/jdk8
ENV JAVA_HOME=/home/exec/jdk8
RUN sed "/securerandom.source=/{s/file:\/dev\/random/file:\/dev\/urandom/}" /home/exec/jdk8/jre/lib/security/java.security -i

ADD dependencies/apache-tomcat-8.0.45.tar.gz /home/exec
RUN /bin/bash -c cd /home/exec; mv /home/exec/apache-tomcat-8.* /home/exec/tomcat
ADD dependencies/server.xml /home/exec/tomcat/conf
ENV CATALINA_HOME=/home/exec/tomcat
ENV TEST_ENV=2
CMD /bin/bash -c cd /home/exec; /home/exec/tomcat/bin/catalina.sh run

ADD dependencies/mooday/my-angular-app.tar.gz /usr/share/nginx/html/

ADD dependencies/*.war /home/exec/tomcat/webapps/swampup.war

#CMD /bin/bash -c cd /home/exec; /home/exec/tomcat/bin/catalina.sh run







